import { createContext, useContext, useState, useCallback, useMemo, useEffect } from 'react'

/**
 * Contexte de langue.
 *
 * Conventions (alignées sur CSFloat et les marketplaces CS2) :
 *  - L'INTERFACE est traduite (filtres, tri, boutons, labels du modal, presets...).
 *  - Les NOMS D'ITEMS restent en anglais ("AWP | Dragon Lore", "Flip Knife |
 *    Gamma Doppler (Factory New)"). Aucun marketplace ne traduit les noms de skins,
 *    de finitions (Gamma Doppler, Fade, Slaughter...) ni les états de wear — on
 *    suit cette logique. Les noms d'items sont des identifiants stables.
 *  - StatTrak™ conserve son ™ dans toutes les langues (comme CSFloat/Skinport).
 *
 * ~10 langues les plus parlées/utilisées : EN, ES, FR, DE, RU, PT, JA, ZH, AR, HI.
 */

export const LANGUAGES = [
  { code: 'EN', name: 'English', flag: '🇬🇧' },
  { code: 'ES', name: 'Español', flag: '🇪🇸' },
  { code: 'FR', name: 'Français', flag: '🇫🇷' },
  { code: 'DE', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'RU', name: 'Русский', flag: '🇷🇺' },
  { code: 'PT', name: 'Português', flag: '🇵🇹' },
  { code: 'JA', name: '日本語', flag: '🇯🇵' },
  { code: 'ZH', name: '中文', flag: '🇨🇳' },
  { code: 'AR', name: 'العربية', flag: '🇸🇦' },
  { code: 'HI', name: 'हिन्दी', flag: '🇮🇳' },
]

const STORAGE_KEY = 'tp-language'

// Clés de traduction. Les noms d'items / wear / rareté ne sont PAS traduits
// (convention marketplaces CS2). Seule l'interface l'est.
const STRINGS = {
  EN: {
    'nav.home': 'Home', 'nav.analytics': 'Analytics', 'nav.market': 'Market', 'nav.dataMarket': 'Data Market',
    'nav.signIn': 'Sign In',
    'filter.search': 'Search', 'filter.searchPlaceholder': 'Search for items...',
    'filter.price': 'Price', 'filter.float': 'Float', 'filter.wear': 'Wear', 'filter.listing': 'Listing',
    'filter.special': 'Special', 'filter.collection': 'Collection', 'filter.stickers': 'Stickers',
    'filter.patterns': 'Patterns', 'filter.sortBy': 'Sort By',
    'sort.priceAsc': 'Price: Low to High', 'sort.priceDesc': 'Price: High to Low',
    'sort.nameAsc': 'Name: A to Z', 'sort.nameDesc': 'Name: Z to A',
    'sort.floatAsc': 'Float: Low to High', 'sort.floatDesc': 'Float: High to Low',
    'filter.any': 'Any', 'filter.anySlot': 'Any Slot',
    'special.stattrak': 'StatTrak™', 'special.souvenir': 'Souvenir',
    'special.highlight': 'Highlight', 'special.normal': 'Normal',
    'listing.all': 'All', 'listing.buynow': 'Buy Now', 'listing.auction': 'Auction',
    'wear.fn': 'Factory New', 'wear.mw': 'Minimal Wear', 'wear.ft': 'Field-Tested',
    'wear.ww': 'Well-Worn', 'wear.bs': 'Battle-Scarred',
    'pattern.fade': 'Fade', 'pattern.doppler': 'Doppler', 'pattern.marbleFade': 'Marble Fade',
    'pattern.caseHardened': 'Case Hardened', 'pattern.tigerTooth': 'Tiger Tooth',
    'pattern.fadePercent': 'Fade %', 'pattern.bluePercent': 'Blue %',
    'collection.filterPlaceholder': 'Filter collections...', 'collection.noMatch': 'No matching collection',
    'sticker.placeholder': 'Sticker', 'sticker.anySlotLabel': 'Any Slot',
    'sticker.slotLabel': 'Slot', 'sticker.hint': '« Any Slot » = with or without sticker',
    'category.all': 'All',
    'grid.loading': 'Loading...', 'grid.items': 'items', 'grid.noResults': 'No items match your filters.',
    'grid.error': 'Failed to load:', 'grid.prev': '← Prev', 'grid.next': 'Next →', 'grid.page': 'Page',
    'modal.float': 'Float', 'modal.wear': 'Wear', 'modal.rarity': 'Rarity', 'modal.platform': 'Platform',
    'modal.price': 'Price', 'modal.priceHistory': 'Price History (30 days)', 'modal.noData': 'No data',
    'modal.buyNow': 'Buy Now', 'modal.addToCart': 'Add to Cart',
    'modal.category': 'Category', 'modal.volume': 'Volume', 'modal.lastUpdated': 'Last Updated',
    'common.na': 'N/A',
  },
  ES: {
    'nav.home': 'Inicio', 'nav.analytics': 'Analíticas', 'nav.market': 'Mercado', 'nav.dataMarket': 'Datos',
    'nav.signIn': 'Iniciar sesión',
    'filter.search': 'Buscar', 'filter.searchPlaceholder': 'Buscar artículos...',
    'filter.price': 'Precio', 'filter.float': 'Float', 'filter.wear': 'Desgaste', 'filter.listing': 'Listado',
    'filter.special': 'Especial', 'filter.collection': 'Colección', 'filter.stickers': 'Pegatinas',
    'filter.patterns': 'Patrones', 'filter.sortBy': 'Ordenar por',
    'sort.priceAsc': 'Precio: de menor a mayor', 'sort.priceDesc': 'Precio: de mayor a menor',
    'sort.nameAsc': 'Nombre: A a Z', 'sort.nameDesc': 'Nombre: Z a A',
    'sort.floatAsc': 'Float: de menor a mayor', 'sort.floatDesc': 'Float: de mayor a menor',
    'filter.any': 'Cualquiera', 'filter.anySlot': 'Cualquier ranura',
    'special.stattrak': 'StatTrak™', 'special.souvenir': 'Souvenir',
    'special.highlight': 'Destacado', 'special.normal': 'Normal',
    'listing.all': 'Todos', 'listing.buynow': 'Comprar ya', 'listing.auction': 'Subasta',
    'wear.fn': 'Factory New', 'wear.mw': 'Minimal Wear', 'wear.ft': 'Field-Tested',
    'wear.ww': 'Well-Worn', 'wear.bs': 'Battle-Scarred',
    'pattern.fade': 'Fade', 'pattern.doppler': 'Doppler', 'pattern.marbleFade': 'Marble Fade',
    'pattern.caseHardened': 'Case Hardened', 'pattern.tigerTooth': 'Tiger Tooth',
    'pattern.fadePercent': 'Fade %', 'pattern.bluePercent': 'Blue %',
    'collection.filterPlaceholder': 'Filtrar colecciones...', 'collection.noMatch': 'Sin coincidencias',
    'sticker.placeholder': 'Pegatina', 'sticker.anySlotLabel': 'Cualquier ranura',
    'sticker.slotLabel': 'Ranura', 'sticker.hint': '« Cualquier ranura » = con o sin pegatina',
    'category.all': 'Todos',
    'grid.loading': 'Cargando...', 'grid.items': 'artículos', 'grid.noResults': 'No hay artículos que coincidan.',
    'grid.error': 'Error al cargar:', 'grid.prev': '← Anterior', 'grid.next': 'Siguiente →', 'grid.page': 'Página',
    'modal.float': 'Float', 'modal.wear': 'Desgaste', 'modal.rarity': 'Rareza', 'modal.platform': 'Plataforma',
    'modal.price': 'Precio', 'modal.priceHistory': 'Historial de precios (30 días)', 'modal.noData': 'Sin datos',
    'modal.buyNow': 'Comprar ya', 'modal.addToCart': 'Añadir al carrito',
    'modal.category': 'Categoría', 'modal.volume': 'Volumen', 'modal.lastUpdated': 'Última actualización',
    'common.na': 'N/D',
  },
  FR: {
    'nav.home': 'Accueil', 'nav.analytics': 'Analytique', 'nav.market': 'Marché', 'nav.dataMarket': 'Données Marché',
    'nav.signIn': 'Se connecter',
    'filter.search': 'Rechercher', 'filter.searchPlaceholder': 'Rechercher des objets...',
    'filter.price': 'Prix', 'filter.float': 'Float', 'filter.wear': 'Wear', 'filter.listing': 'Annonce',
    'filter.special': 'Spécial', 'filter.collection': 'Collection', 'filter.stickers': 'Stickers',
    'filter.patterns': 'Motifs', 'filter.sortBy': 'Trier par',
    'sort.priceAsc': 'Prix : croissant', 'sort.priceDesc': 'Prix : décroissant',
    'sort.nameAsc': 'Nom : A à Z', 'sort.nameDesc': 'Nom : Z à A',
    'sort.floatAsc': 'Float : croissant', 'sort.floatDesc': 'Float : décroissant',
    'filter.any': 'Tous', 'filter.anySlot': 'N\'importe quel emplacement',
    'special.stattrak': 'StatTrak™', 'special.souvenir': 'Souvenir',
    'special.highlight': 'En vedette', 'special.normal': 'Normal',
    'listing.all': 'Tous', 'listing.buynow': 'Acheter', 'listing.auction': 'Enchères',
    'wear.fn': 'Factory New', 'wear.mw': 'Minimal Wear', 'wear.ft': 'Field-Tested',
    'wear.ww': 'Well-Worn', 'wear.bs': 'Battle-Scarred',
    'pattern.fade': 'Fade', 'pattern.doppler': 'Doppler', 'pattern.marbleFade': 'Marble Fade',
    'pattern.caseHardened': 'Case Hardened', 'pattern.tigerTooth': 'Tiger Tooth',
    'pattern.fadePercent': 'Fade %', 'pattern.bluePercent': 'Blue %',
    'collection.filterPlaceholder': 'Filtrer les collections...', 'collection.noMatch': 'Aucune collection',
    'sticker.placeholder': 'Sticker', 'sticker.anySlotLabel': 'N\'importe quel emplacement',
    'sticker.slotLabel': 'Emplacement', 'sticker.hint': '« N\'importe quel emplacement » = avec ou sans sticker',
    'category.all': 'Tous',
    'grid.loading': 'Chargement...', 'grid.items': 'objets', 'grid.noResults': 'Aucun objet ne correspond.',
    'grid.error': 'Échec du chargement :', 'grid.prev': '← Précédent', 'grid.next': 'Suivant →', 'grid.page': 'Page',
    'modal.float': 'Float', 'modal.wear': 'Wear', 'modal.rarity': 'Rareté', 'modal.platform': 'Plateforme',
    'modal.price': 'Prix', 'modal.priceHistory': 'Historique des prix (30 jours)', 'modal.noData': 'Aucune donnée',
    'modal.buyNow': 'Acheter', 'modal.addToCart': 'Ajouter au panier',
    'modal.category': 'Catégorie', 'modal.volume': 'Volume', 'modal.lastUpdated': 'Dernière mise à jour',
    'common.na': 'N/D',
  },
  DE: {
    'nav.home': 'Start', 'nav.analytics': 'Analytik', 'nav.market': 'Markt', 'nav.dataMarket': 'Daten',
    'nav.signIn': 'Anmelden',
    'filter.search': 'Suche', 'filter.searchPlaceholder': 'Nach Items suchen...',
    'filter.price': 'Preis', 'filter.float': 'Float', 'filter.wear': 'Verschleiß', 'filter.listing': 'Angebot',
    'filter.special': 'Spezial', 'filter.collection': 'Kollektion', 'filter.stickers': 'Aufkleber',
    'filter.patterns': 'Muster', 'filter.sortBy': 'Sortieren nach',
    'sort.priceAsc': 'Preis: niedrig zu hoch', 'sort.priceDesc': 'Preis: hoch zu niedrig',
    'sort.nameAsc': 'Name: A bis Z', 'sort.nameDesc': 'Name: Z bis A',
    'sort.floatAsc': 'Float: niedrig zu hoch', 'sort.floatDesc': 'Float: hoch zu niedrig',
    'filter.any': 'Alle', 'filter.anySlot': 'Beliebiger Slot',
    'special.stattrak': 'StatTrak™', 'special.souvenir': 'Souvenir',
    'special.highlight': 'Hervorgehoben', 'special.normal': 'Normal',
    'listing.all': 'Alle', 'listing.buynow': 'Sofort kaufen', 'listing.auction': 'Auktion',
    'wear.fn': 'Factory New', 'wear.mw': 'Minimal Wear', 'wear.ft': 'Field-Tested',
    'wear.ww': 'Well-Worn', 'wear.bs': 'Battle-Scarred',
    'pattern.fade': 'Fade', 'pattern.doppler': 'Doppler', 'pattern.marbleFade': 'Marble Fade',
    'pattern.caseHardened': 'Case Hardened', 'pattern.tigerTooth': 'Tiger Tooth',
    'pattern.fadePercent': 'Fade %', 'pattern.bluePercent': 'Blue %',
    'collection.filterPlaceholder': 'Kollektionen filtern...', 'collection.noMatch': 'Keine Kollektion',
    'sticker.placeholder': 'Aufkleber', 'sticker.anySlotLabel': 'Beliebiger Slot',
    'sticker.slotLabel': 'Slot', 'sticker.hint': '« Beliebiger Slot » = mit oder ohne Aufkleber',
    'category.all': 'Alle',
    'grid.loading': 'Laden...', 'grid.items': 'Objekte', 'grid.noResults': 'Keine passenden Objekte.',
    'grid.error': 'Laden fehlgeschlagen:', 'grid.prev': '← Zurück', 'grid.next': 'Weiter →', 'grid.page': 'Seite',
    'modal.float': 'Float', 'modal.wear': 'Verschleiß', 'modal.rarity': 'Seltenheit', 'modal.platform': 'Plattform',
    'modal.price': 'Preis', 'modal.priceHistory': 'Preishistorie (30 Tage)', 'modal.noData': 'Keine Daten',
    'modal.buyNow': 'Sofort kaufen', 'modal.addToCart': 'In den Warenkorb',
    'modal.category': 'Kategorie', 'modal.volume': 'Volumen', 'modal.lastUpdated': 'Zuletzt aktualisiert',
    'common.na': 'k. A.',
  },
  RU: {
    'nav.home': 'Главная', 'nav.analytics': 'Аналитика', 'nav.market': 'Маркет', 'nav.dataMarket': 'Данные',
    'nav.signIn': 'Войти',
    'filter.search': 'Поиск', 'filter.searchPlaceholder': 'Поиск предметов...',
    'filter.price': 'Цена', 'filter.float': 'Float', 'filter.wear': 'Износ', 'filter.listing': 'Объявление',
    'filter.special': 'Спец.', 'filter.collection': 'Коллекция', 'filter.stickers': 'Наклейки',
    'filter.patterns': 'Узоры', 'filter.sortBy': 'Сортировка',
    'sort.priceAsc': 'Цена: по возрастанию', 'sort.priceDesc': 'Цена: по убыванию',
    'sort.nameAsc': 'Название: А→Я', 'sort.nameDesc': 'Название: Я→А',
    'sort.floatAsc': 'Float: по возрастанию', 'sort.floatDesc': 'Float: по убыванию',
    'filter.any': 'Любой', 'filter.anySlot': 'Любой слот',
    'special.stattrak': 'StatTrak™', 'special.souvenir': 'Souvenir',
    'special.highlight': 'Выделено', 'special.normal': 'Обычный',
    'listing.all': 'Все', 'listing.buynow': 'Купить', 'listing.auction': 'Аукцион',
    'wear.fn': 'Factory New', 'wear.mw': 'Minimal Wear', 'wear.ft': 'Field-Tested',
    'wear.ww': 'Well-Worn', 'wear.bs': 'Battle-Scarred',
    'pattern.fade': 'Fade', 'pattern.doppler': 'Doppler', 'pattern.marbleFade': 'Marble Fade',
    'pattern.caseHardened': 'Case Hardened', 'pattern.tigerTooth': 'Tiger Tooth',
    'pattern.fadePercent': 'Fade %', 'pattern.bluePercent': 'Blue %',
    'collection.filterPlaceholder': 'Фильтр коллекций...', 'collection.noMatch': 'Коллекций нет',
    'sticker.placeholder': 'Наклейка', 'sticker.anySlotLabel': 'Любой слот',
    'sticker.slotLabel': 'Слот', 'sticker.hint': '« Любой слот » = с или без наклейки',
    'category.all': 'Все',
    'grid.loading': 'Загрузка...', 'grid.items': 'предметов', 'grid.noResults': 'Нет предметов по фильтрам.',
    'grid.error': 'Ошибка загрузки:', 'grid.prev': '← Назад', 'grid.next': 'Далее →', 'grid.page': 'Стр.',
    'modal.float': 'Float', 'modal.wear': 'Износ', 'modal.rarity': 'Редкость', 'modal.platform': 'Платформа',
    'modal.price': 'Цена', 'modal.priceHistory': 'История цен (30 дней)', 'modal.noData': 'Нет данных',
    'modal.buyNow': 'Купить', 'modal.addToCart': 'В корзину',
    'modal.category': 'Категория', 'modal.volume': 'Объём', 'modal.lastUpdated': 'Обновлено',
    'common.na': 'н/д',
  },
  PT: {
    'nav.home': 'Início', 'nav.analytics': 'Analíticos', 'nav.market': 'Mercado', 'nav.dataMarket': 'Dados',
    'nav.signIn': 'Entrar',
    'filter.search': 'Buscar', 'filter.searchPlaceholder': 'Buscar itens...',
    'filter.price': 'Preço', 'filter.float': 'Float', 'filter.wear': 'Desgaste', 'filter.listing': 'Listagem',
    'filter.special': 'Especial', 'filter.collection': 'Coleção', 'filter.stickers': 'Adesivos',
    'filter.patterns': 'Padrões', 'filter.sortBy': 'Ordenar por',
    'sort.priceAsc': 'Preço: menor p/ maior', 'sort.priceDesc': 'Preço: maior p/ menor',
    'sort.nameAsc': 'Nome: A a Z', 'sort.nameDesc': 'Nome: Z a A',
    'sort.floatAsc': 'Float: menor p/ maior', 'sort.floatDesc': 'Float: maior p/ menor',
    'filter.any': 'Qualquer', 'filter.anySlot': 'Qualquer espaço',
    'special.stattrak': 'StatTrak™', 'special.souvenir': 'Souvenir',
    'special.highlight': 'Destaque', 'special.normal': 'Normal',
    'listing.all': 'Todos', 'listing.buynow': 'Comprar', 'listing.auction': 'Leilão',
    'wear.fn': 'Factory New', 'wear.mw': 'Minimal Wear', 'wear.ft': 'Field-Tested',
    'wear.ww': 'Well-Worn', 'wear.bs': 'Battle-Scarred',
    'pattern.fade': 'Fade', 'pattern.doppler': 'Doppler', 'pattern.marbleFade': 'Marble Fade',
    'pattern.caseHardened': 'Case Hardened', 'pattern.tigerTooth': 'Tiger Tooth',
    'pattern.fadePercent': 'Fade %', 'pattern.bluePercent': 'Blue %',
    'collection.filterPlaceholder': 'Filtrar coleções...', 'collection.noMatch': 'Sem coleções',
    'sticker.placeholder': 'Adesivo', 'sticker.anySlotLabel': 'Qualquer espaço',
    'sticker.slotLabel': 'Espaço', 'sticker.hint': '« Qualquer espaço » = com ou sem adesivo',
    'category.all': 'Todos',
    'grid.loading': 'Carregando...', 'grid.items': 'itens', 'grid.noResults': 'Nenhum item corresponde.',
    'grid.error': 'Falha ao carregar:', 'grid.prev': '← Anterior', 'grid.next': 'Próximo →', 'grid.page': 'Pág.',
    'modal.float': 'Float', 'modal.wear': 'Desgaste', 'modal.rarity': 'Raridade', 'modal.platform': 'Plataforma',
    'modal.price': 'Preço', 'modal.priceHistory': 'Histórico de preços (30 dias)', 'modal.noData': 'Sem dados',
    'modal.buyNow': 'Comprar', 'modal.addToCart': 'Adicionar ao carrinho',
    'modal.category': 'Categoria', 'modal.volume': 'Volume', 'modal.lastUpdated': 'Última atualização',
    'common.na': 'N/D',
  },
  JA: {
    'nav.home': 'ホーム', 'nav.analytics': '分析', 'nav.market': 'マーケット', 'nav.dataMarket': 'データ',
    'nav.signIn': 'サインイン',
    'filter.search': '検索', 'filter.searchPlaceholder': 'アイテムを検索...',
    'filter.price': '価格', 'filter.float': 'Float', 'filter.wear': '磨耗', 'filter.listing': '出品',
    'filter.special': 'スペシャル', 'filter.collection': 'コレクション', 'filter.stickers': 'ステッカー',
    'filter.patterns': 'パターン', 'filter.sortBy': '並べ替え',
    'sort.priceAsc': '価格: 安い順', 'sort.priceDesc': '価格: 高い順',
    'sort.nameAsc': '名前: A→Z', 'sort.nameDesc': '名前: Z→A',
    'sort.floatAsc': 'Float: 低い順', 'sort.floatDesc': 'Float: 高い順',
    'filter.any': 'すべて', 'filter.anySlot': '任意のスロット',
    'special.stattrak': 'StatTrak™', 'special.souvenir': 'Souvenir',
    'special.highlight': 'ハイライト', 'special.normal': 'ノーマル',
    'listing.all': 'すべて', 'listing.buynow': '即購入', 'listing.auction': 'オークション',
    'wear.fn': 'Factory New', 'wear.mw': 'Minimal Wear', 'wear.ft': 'Field-Tested',
    'wear.ww': 'Well-Worn', 'wear.bs': 'Battle-Scarred',
    'pattern.fade': 'Fade', 'pattern.doppler': 'Doppler', 'pattern.marbleFade': 'Marble Fade',
    'pattern.caseHardened': 'Case Hardened', 'pattern.tigerTooth': 'Tiger Tooth',
    'pattern.fadePercent': 'Fade %', 'pattern.bluePercent': 'Blue %',
    'collection.filterPlaceholder': 'コレクションを絞り込み...', 'collection.noMatch': '該当なし',
    'sticker.placeholder': 'ステッカー', 'sticker.anySlotLabel': '任意のスロット',
    'sticker.slotLabel': 'スロット', 'sticker.hint': '« 任意のスロット » = ステッカーの有無問わず',
    'category.all': 'すべて',
    'grid.loading': '読み込み中...', 'grid.items': 'アイテム', 'grid.noResults': '該当するアイテムがありません。',
    'grid.error': '読み込み失敗:', 'grid.prev': '← 前へ', 'grid.next': '次へ →', 'grid.page': 'ページ',
    'modal.float': 'Float', 'modal.wear': '磨耗', 'modal.rarity': 'レアリティ', 'modal.platform': 'プラットフォーム',
    'modal.price': '価格', 'modal.priceHistory': '価格推移 (30日)', 'modal.noData': 'データなし',
    'modal.buyNow': '即購入', 'modal.addToCart': 'カートに追加',
    'modal.category': 'カテゴリー', 'modal.volume': '取引量', 'modal.lastUpdated': '最終更新',
    'common.na': 'なし',
  },
  ZH: {
    'nav.home': '首页', 'nav.analytics': '分析', 'nav.market': '市场', 'nav.dataMarket': '数据',
    'nav.signIn': '登录',
    'filter.search': '搜索', 'filter.searchPlaceholder': '搜索物品...',
    'filter.price': '价格', 'filter.float': 'Float', 'filter.wear': '磨损', 'filter.listing': '挂单',
    'filter.special': '特殊', 'filter.collection': '收藏品', 'filter.stickers': '贴纸',
    'filter.patterns': '图案', 'filter.sortBy': '排序',
    'sort.priceAsc': '价格：从低到高', 'sort.priceDesc': '价格：从高到低',
    'sort.nameAsc': '名称：A 到 Z', 'sort.nameDesc': '名称：Z 到 A',
    'sort.floatAsc': 'Float：从低到高', 'sort.floatDesc': 'Float：从高到低',
    'filter.any': '任意', 'filter.anySlot': '任意位置',
    'special.stattrak': 'StatTrak™', 'special.souvenir': 'Souvenir',
    'special.highlight': '高亮', 'special.normal': '普通',
    'listing.all': '全部', 'listing.buynow': '立即购买', 'listing.auction': '拍卖',
    'wear.fn': 'Factory New', 'wear.mw': 'Minimal Wear', 'wear.ft': 'Field-Tested',
    'wear.ww': 'Well-Worn', 'wear.bs': 'Battle-Scarred',
    'pattern.fade': 'Fade', 'pattern.doppler': 'Doppler', 'pattern.marbleFade': 'Marble Fade',
    'pattern.caseHardened': 'Case Hardened', 'pattern.tigerTooth': 'Tiger Tooth',
    'pattern.fadePercent': 'Fade %', 'pattern.bluePercent': 'Blue %',
    'collection.filterPlaceholder': '筛选收藏品...', 'collection.noMatch': '无匹配收藏品',
    'sticker.placeholder': '贴纸', 'sticker.anySlotLabel': '任意位置',
    'sticker.slotLabel': '位置', 'sticker.hint': '« 任意位置 » = 有无贴纸均可',
    'category.all': '全部',
    'grid.loading': '加载中...', 'grid.items': '件物品', 'grid.noResults': '没有匹配的物品。',
    'grid.error': '加载失败：', 'grid.prev': '← 上一页', 'grid.next': '下一页 →', 'grid.page': '页',
    'modal.float': 'Float', 'modal.wear': '磨损', 'modal.rarity': '稀有度', 'modal.platform': '平台',
    'modal.price': '价格', 'modal.priceHistory': '价格历史 (30天)', 'modal.noData': '无数据',
    'modal.buyNow': '立即购买', 'modal.addToCart': '加入购物车',
    'modal.category': '类别', 'modal.volume': '成交量', 'modal.lastUpdated': '最后更新',
    'common.na': '无',
  },
  AR: {
    'nav.home': 'الرئيسية', 'nav.analytics': 'التحليلات', 'nav.market': 'السوق', 'nav.dataMarket': 'البيانات',
    'nav.signIn': 'تسجيل الدخول',
    'filter.search': 'بحث', 'filter.searchPlaceholder': 'ابحث عن العناصر...',
    'filter.price': 'السعر', 'filter.float': 'Float', 'filter.wear': 'التآكل', 'filter.listing': 'الإدراج',
    'filter.special': 'خاص', 'filter.collection': 'المجموعة', 'filter.stickers': 'ملصقات',
    'filter.patterns': 'الأنماط', 'filter.sortBy': 'ترتيب حسب',
    'sort.priceAsc': 'السعر: من الأقل للأعلى', 'sort.priceDesc': 'السعر: من الأعلى للأقل',
    'sort.nameAsc': 'الاسم: A إلى Z', 'sort.nameDesc': 'الاسم: Z إلى A',
    'sort.floatAsc': 'Float: من الأقل للأعلى', 'sort.floatDesc': 'Float: من الأعلى للأقل',
    'filter.any': 'أي', 'filter.anySlot': 'أي خانة',
    'special.stattrak': 'StatTrak™', 'special.souvenir': 'Souvenir',
    'special.highlight': 'مميز', 'special.normal': 'عادي',
    'listing.all': 'الكل', 'listing.buynow': 'اشترِ الآن', 'listing.auction': 'مزاد',
    'wear.fn': 'Factory New', 'wear.mw': 'Minimal Wear', 'wear.ft': 'Field-Tested',
    'wear.ww': 'Well-Worn', 'wear.bs': 'Battle-Scarred',
    'pattern.fade': 'Fade', 'pattern.doppler': 'Doppler', 'pattern.marbleFade': 'Marble Fade',
    'pattern.caseHardened': 'Case Hardened', 'pattern.tigerTooth': 'Tiger Tooth',
    'pattern.fadePercent': 'Fade %', 'pattern.bluePercent': 'Blue %',
    'collection.filterPlaceholder': 'تصفية المجموعات...', 'collection.noMatch': 'لا مجموعات',
    'sticker.placeholder': 'ملصق', 'sticker.anySlotLabel': 'أي خانة',
    'sticker.slotLabel': 'الخانة', 'sticker.hint': '« أي خانة » = مع أو بدون ملصق',
    'category.all': 'الكل',
    'grid.loading': 'جارٍ التحميل...', 'grid.items': 'عنصر', 'grid.noResults': 'لا توجد عناصر مطابقة.',
    'grid.error': 'فشل التحميل:', 'grid.prev': '← السابق', 'grid.next': 'التالي →', 'grid.page': 'صفحة',
    'modal.float': 'Float', 'modal.wear': 'التآكل', 'modal.rarity': 'الندرة', 'modal.platform': 'المنصة',
    'modal.price': 'السعر', 'modal.priceHistory': 'سجل الأسعار (30 يوم)', 'modal.noData': 'لا بيانات',
    'modal.buyNow': 'اشترِ الآن', 'modal.addToCart': 'أضف للسلة',
    'modal.category': 'الفئة', 'modal.volume': 'الحجم', 'modal.lastUpdated': 'آخر تحديث',
    'common.na': 'لا',
  },
  HI: {
    'nav.home': 'होम', 'nav.analytics': 'विश्लेषण', 'nav.market': 'बाज़ार', 'nav.dataMarket': 'डेटा',
    'nav.signIn': 'साइन इन',
    'filter.search': 'खोज', 'filter.searchPlaceholder': 'वस्तुएँ खोजें...',
    'filter.price': 'मूल्य', 'filter.float': 'Float', 'filter.wear': 'घिसाव', 'filter.listing': 'सूची',
    'filter.special': 'विशेष', 'filter.collection': 'संग्रह', 'filter.stickers': 'स्टिकर',
    'filter.patterns': 'पैटर्न', 'filter.sortBy': 'क्रमबद्ध करें',
    'sort.priceAsc': 'मूल्य: कम से अधिक', 'sort.priceDesc': 'मूल्य: अधिक से कम',
    'sort.nameAsc': 'नाम: A से Z', 'sort.nameDesc': 'नाम: Z से A',
    'sort.floatAsc': 'Float: कम से अधिक', 'sort.floatDesc': 'Float: अधिक से कम',
    'filter.any': 'कोई भी', 'filter.anySlot': 'कोई भी स्लॉट',
    'special.stattrak': 'StatTrak™', 'special.souvenir': 'Souvenir',
    'special.highlight': 'हाइलाइट', 'special.normal': 'सामान्य',
    'listing.all': 'सभी', 'listing.buynow': 'अभी खरीदें', 'listing.auction': 'नीलामी',
    'wear.fn': 'Factory New', 'wear.mw': 'Minimal Wear', 'wear.ft': 'Field-Tested',
    'wear.ww': 'Well-Worn', 'wear.bs': 'Battle-Scarred',
    'pattern.fade': 'Fade', 'pattern.doppler': 'Doppler', 'pattern.marbleFade': 'Marble Fade',
    'pattern.caseHardened': 'Case Hardened', 'pattern.tigerTooth': 'Tiger Tooth',
    'pattern.fadePercent': 'Fade %', 'pattern.bluePercent': 'Blue %',
    'collection.filterPlaceholder': 'संग्रह फ़िल्टर करें...', 'collection.noMatch': 'कोई संग्रह नहीं',
    'sticker.placeholder': 'स्टिकर', 'sticker.anySlotLabel': 'कोई भी स्लॉट',
    'sticker.slotLabel': 'स्लॉट', 'sticker.hint': '« कोई भी स्लॉट » = स्टिकर के साथ या बिना',
    'category.all': 'सभी',
    'grid.loading': 'लोड हो रहा है...', 'grid.items': 'वस्तुएँ', 'grid.noResults': 'कोई वस्तु मेल नहीं खाती।',
    'grid.error': 'लोड विफल:', 'grid.prev': '← पिछला', 'grid.next': 'अगला →', 'grid.page': 'पृष्ठ',
    'modal.float': 'Float', 'modal.wear': 'घिसाव', 'modal.rarity': 'दुर्लभता', 'modal.platform': 'प्लेटफ़ॉर्म',
    'modal.price': 'मूल्य', 'modal.priceHistory': 'मूल्य इतिहास (30 दिन)', 'modal.noData': 'कोई डेटा नहीं',
    'modal.buyNow': 'अभी खरीदें', 'modal.addToCart': 'कार्ट में जोड़ें',
    'modal.category': 'श्रेणी', 'modal.volume': 'वॉल्यूम', 'modal.lastUpdated': 'अंतिम अपडेट',
    'common.na': 'लागू नहीं',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      return localStorage.getItem(STORAGE_KEY) || 'EN'
    } catch {
      return 'EN'
    }
  })

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, language)
    } catch {
      /* ignore */
    }
    document.documentElement.lang = language.toLowerCase()
    // L'arabe s'écrit de droite à gauche.
    document.documentElement.dir = language === 'AR' ? 'rtl' : 'ltr'
  }, [language])

  const changeLanguage = useCallback((code) => setLanguage(code), [])

  const t = useCallback(
    (key) => (STRINGS[language] && STRINGS[language][key]) || STRINGS.EN[key] || key,
    [language],
  )

  const value = useMemo(
    () => ({ language, languages: LANGUAGES, changeLanguage, t }),
    [language, changeLanguage, t],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage doit être utilisé dans <LanguageProvider>')
  return ctx
}
